#ifndef RDEF_MDEC
#define RDEF_MDEC

#include "../util.h"

enum {
	STAT_NWORDS = BIT_RANGE(0, 16),
#define STAT_NWORDS_SET(o, v) SET_BITS(o, v, STAT_NWORDS, 0)
#define STAT_NWORDS_GET(o) GET_BITS(o, STAT_NWORDS, 0)
	
	STAT_CURBLK = BIT_RANGE(16, 3),
#define STAT_CURBLK_SET(o, v) SET_BITS(o, v, STAT_CURBLK, 16)
#define STAT_CURBLK_GET(o) GET_BITS(o, STAT_CURBLK, 16)
	
	STAT_OUTMASK = BIT(23),
	STAT_OUTSIGN = BIT(24),
	STAT_OUTDEPTH = BIT_RANGE(25, 2),
#define STAT_OUTDEPTH_SET(o, v) SET_BITS(o, v, STAT_OUTDEPTH, 25)
#define STAT_OUTDEPTH_GET(o) GET_BITS(o, STAT_OUTDEPTH, 25)

	STAT_DATA_OUT_REQ = BIT(27),
	STAT_DATA_IN_REQ = BIT(28),
	STAT_BUSY = BIT(29),
	STAT_IN_FULL = BIT(30),
	STAT_OUT_EMPTY = BIT(31),
};

enum {
	CTRL_DATA_OUT_EN = BIT(29),
	CTRL_DATA_IN_EN = BIT(30),
	CTRL_RESET = BIT(31),
};

#endif
