#ifndef RDEF_TIMER
#define RDEF_TIMER

#include "../util.h"

enum {
	MODE_SYNC_EN = BIT(0),
	MODE_SYNC = BIT_RANGE(1, 2),
#define MODE_SYNC_GET(o) GET_BITS(o, MODE_SYNC, 1)
#define MODE_SYNC_SET(o, v) SET_BITS(o, v, MODE_SYNC, 1)
	
	MODE_RESET_ON_TARGET = BIT(3),
	MODE_IRQ_ON_TARGET = BIT(4),
	MODE_IRQ_ON_MAX = BIT(5),
	MODE_IRQ_REPEAT = BIT(6),
	MODE_IRQ_TOGGLE = BIT(7),
	MODE_CLK_SRC = BIT_RANGE(8, 2),
#define MODE_CLK_SRC_GET(o) GET_BITS(o, MODE_CLK_SRC, 8)
#define MODE_CLK_SRC_SET(o, v) SET_BITS(o, v, MODE_CLK_SRC, 8)

	MODE_NO_IRQ = BIT(10),
	MODE_TARGET_REACHED = BIT(11),
	MODE_MAX_REACHED = BIT(12)
};

#endif
